 /******************************************************************************
 *
 * Module: ULTRASONIC
 *
 * File Name: ultrasonic.c
 *
 * Description: Source file for the Ultrasonic driver
 *
 * Author: Youssef Abuzeid
 *
 *******************************************************************************/



#include "gpio.h"
#include "icu.h"
#include "ultrasonic.h"
#include "util\delay.h"

ICU_ConfigType ICU_configurations={F_CPU_8,RAISING};

uint8 g_edge=0;
uint16 ICU_highTime=0;

/*
 * Description :
 * Initialize the ICU driver as required.
 * Setup the ICU call back function.
 * Setup the direction for the trigger pin as output pin through the GPIO driver.
 */
void Ultrasonic_init(void){
	/*
	 * initialize the ICU driver
	 */
	ICU_init(&ICU_configurations);
	/*
	 * give the ICU the callback function
	 */
	ICU_setCallBack(Ultrasonic_edgeProcessing);
	/*
	 * setup the TRIGGER pin as output
	 */
	GPIO_setupPinDirection(TRIGGER_PORT_ID,TRIGGER_PIN_ID,PIN_OUTPUT);
}

/*
 * Description :
 * Send the Trigger pulse to the ultrasonic.
 */
void Ultrasonic_Trigger(void){
	GPIO_writePin(TRIGGER_PORT_ID,TRIGGER_PIN_ID,LOGIC_HIGH);
	_delay_ms(10);
	GPIO_writePin(TRIGGER_PORT_ID,TRIGGER_PIN_ID,LOGIC_LOW);
}

/*
 * Description :
 *  Send the trigger pulse by using Ultrasonic_Trigger function.
 *	Start the measurements by the ICU from this moment.
 */
uint16 Ultrasonic_readDistance(void){
	/* Set Edge Type to Raising to start measuring*/
	ICU_setEdgeDetectionType(RAISING);

	uint16 distance=0;
	g_edge=0;
	/*
	 * send trigger pulse to the ultrasonic
	 */
	Ultrasonic_Trigger();
	/*
	 * wait for the echo
	 */
	while(g_edge!=2);

	//distance=17000*((float)ICU_highTime/F_TIME);
	/*
	 * calculate the distance
	 */
	distance=(ICU_highTime/58)+1 ;

	return distance;

}

/*
 * Description :
 *   This is the call back function called by the ICU driver.
 *   This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void){
	g_edge++;
	if(g_edge==1){
		/*
		 * clear the timer to calculate high time
		 */
		ICU_clearTimerValue();
		/*
		 * set the edge type to falling
		 */
		ICU_setEdgeDetectionType(FALLING);
	}else if(g_edge==2){
		ICU_highTime=ICU_getInputCaptureValue();



	}

}




